### ISSUE TITLE
please add .gitignore

### ISSUE THREAD

**Issue by berdachuk** [DankoDmitriy/JavaStart#1]
please add .gitignore file and remove IDE specific files like .idea folder

**Comment by DankoDmitriy** [comment]
Good afternoon. I created .gitignore, but I can't delete folder .idea from github.
I read  mans, and used this commands:

`git rm -f .idea -f
git commit -m 'Commit name'
git push.
`
Git return me this comment: 

`fatal: pathspec '.idea' did not match any files`

Could you tell me what I need to read to fix this error. Thanks.

**Comment by berdachuk** [comment]
.idea was removed, no problems now
